### PR TITLE
Hatibranch

### LINKED ISSUE #102: Implement archetype action: Draconic Knight - Beast Slash
# Dependencies
- [x] DemoDemons/design#169

# Related design entries
* https://github.com/EveryoneDestroysTheWorld/design/blob/main/inventory/archetypes/draconic-knight.md

# Completion criteria
- [x] Let the player swipe on every primary action button click.
- [x] Reasonably reduce stamina.
- [x] Let the player charge the swipe by holding the button.
- [x] Make sure this is only works while grounded, not flying.

### PR DESCRIPTION
**Pull request by zriku1**
Added two actions for draconic knight
1 action animation
2 melee attack animations

### CODE REVIEW

**Comment by Christian-Toney** [comment]
Finishing up review in the morning

**Comment by Christian-Toney** [comment]
All errors fixed; testing now

**Review by Christian-Toney — APPROVED** [review]
all good :)

**Comment by zriku1** [comment]
Known issues:
1 and Q have infinite range
Fire Claw effect does not light enemies on fire

**Pull request merged**
